### ISSUE TITLE
Fix ASAS-SN import line

### ISSUE THREAD

**Issue by jrastinejad** [SAGUARO-MMA/kne-cand-vetting#1]
needed in order to query catalog

**Comment by jrastinejad** [comment]
Sent you an email at 1:53 pm - can resend if it didn't go through?

**Comment by pndaly** [comment]
Ah, OK. I see it now. Will check it out. P

**Comment by pndaly** [comment]
First problem is that the Asassn database record is not called AsAssnQ3cRecord(...) at line 151 but ASASSNQ3cRecord(...)!
Second, the failure is at line 107/108 ... milliquas not asassn! Will see what's going on there.

**Comment by pndaly** [comment]
Huh, there is obviously a circularity problem that I don't yet understand. You actually only need to import the _cli code as
that imports the _filters which in turn imports the _orm. So:

from sassy_src.models.milliquas_q3c_orm_cli import *
from sassy_src.models.asassn_q3c_orm_cli import *

If you do that the problem persists. However, if you reverse the order, the code runs successfully!

from sassy_src.models.asassn_q3c_orm_cli import *
from sassy_src.models.milliquas_q3c_orm_cli import *

That will get you running but I'll plug away and see if I can see why it works one way and not the other.

P

**Comment by jrastinejad** [comment]
Thanks a lot, Phil! Sorry for the slow response - I was traveling all day. Will take a look Monday. 

And don’t worry Dave, I’ll make sure to comment on the issue!!!

**Comment by jrastinejad** [comment]
All fixed! Thanks again, Phil
