### ISSUE TITLE
Catalogs to Upload to SASSy

### ISSUE THREAD

**Issue by jrastinejad** [SAGUARO-MMA/kne-cand-vetting#3]
As of 5/5/22:

Uploaded: GLADE, HECATE, GWGC, million quasar, ASAS-SN variable star

Waiting on: 
- Gaia (wait for new eDR3?)
- SDSS (Griffin sent Phil)
- Legacy survey photo-z (waiting to find)
- PS1 STRM photo-z

**Comment by jrastinejad** [comment]
Hi Phil, I've incorporated all the uploaded catalogs listed above. Let me know when you have the chance to uploading the remaining catalogs - thanks!

**Comment by pndaly** [comment]
I've lost Griffin's email about where he put the SDSS catalog. Please re-send. However, I found a file on beast in /home/griffin called sdss12_photometric_catalog.csv dated 04/29/2022 and assume that is it but it's not the same as a previously identified catalog found here: https://www.sdss.org/dr16/algorithms/qso_catalog/. Which one is correct or do you want both?

**Comment by griffin-h** [comment]
That CSV file should be correct. Jillian and I determined that that was the catalog she was using, not the one she previously sent.

[I sent this by email on May 17, and I don't know why it didn't get through...]

**Comment by jrastinejad** [comment]
Hi Phil,

Thanks again for uploading the SDSS DR12 catalog. Are you planning on making the same filter functions for this catalog as you made for GLADE, HECATE & GWGC? I don’t currently see them in /home/phil_daly/SASSyII/sassy_src/models/.
Thanks,
Jillian
