### ISSUE TITLE
Archival image to display on candidate page

### ISSUE THREAD

**Issue by jrastinejad** [SAGUARO-MMA/kne-cand-vetting#4]
Need to figure out best way to get an archival image of candidate field to display with host galaxy labels on candidate page. Ideally want to make a plan for:

Which catalogs to pull from? How does catalog priority depend on sky location? Should we save image or pull up a new one every time (how much time does this take?)? What does snex do? Should go in galaxy function or be separate?

**Comment by griffin-h** [comment]
SNEx does some complicated priority according to the sky position: I think it's PS1 3π, SDSS, DECam, POSS. All of these are accessible via API. But I always thought it might be better just to embed the Aladin viewer, like the TNS does.

On the other hand, if we are predownloading a template for every field we'll be observing, we could potentially make our own cutouts and display them.

**Comment by jrastinejad** [comment]
Okay, good to know. @dsand made the point that if we're ingesting candidates from other groups, we won't have cutouts for some candidates so perhaps Aladin is the way to go?

**Comment by dsand** [comment]
I like the Aladin suggestion.

**Comment by griffin-h** [comment]
@jrastinejad is going to look into whether it's possible to plot regions on top of Aladin, e.g. for galaxy crossmatches

**Comment by dsand** [comment]
I would just ask Sam Wyatt about this.  They seem to do it for the Treasure Map.

**Comment by jrastinejad** [comment]
Great, I'll message him Monday

**Comment by griffin-h** [comment]
We solved the plotting of regions on top of the Aladin viewer.
