### ISSUE TITLE
Update on current capabilities and what's missing

### ISSUE THREAD

**Issue by dsand** [SAGUARO-MMA/kne-cand-vetting#9]
Update the readme of this repo (or some of other type of documentation), so we know what has been implemented thus far.  If there is a list of things in the operations plan that have not been implemented yet, it would be good to know those too.

**Comment by jrastinejad** [comment]
Updated the readme and added citations for catalogs. Double-checked that catalogs in operations plan have been implemented with exception of full implementation of LS DR 10 (see other issue) and PS1 detection catalog.
